{
 "title": "Taxy NY model linear regresor",
 "time": { "from": "2022-02-01T03:04:46.000Z", "to": "2022-02-28T18:58:23.000Z" },
 "panels": [
  {
   "title": "Prediction drift 2022-02",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", prediction_drift FROM evidently_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Share missing values 2022-02",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT share_missing_values, \"timestamp\" FROM evidently_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Columns num drifted 2022-02",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", num_drifted_columns FROM evidently_metrics LIMIT 50 "
    }
   ]
  }
 ]
}